### ISSUE TITLE
Week 06 Teachers Solution is not correct

### ISSUE THREAD

**Issue by decreo17** [byui-cs/CS246#11]
The week 6  team activity teacher's solution in the link below does not count even or odd, it starts either by one or two and just continues counting regardless if it's odd or even.

https://byui-cs.github.io/cs246-faculty/28321883-07a1-48bc-bdaa-2b6aea1e9b61/#mainactivity.java

**Comment by macbeth-byui** [comment]
Thanks @decreo17 for notifying us about this error in the code.  Its more fun when the counter increments by 2 each time.  I have pushed the changed.  Thanks again!
